"use client";
import { AlertTriangle, ArrowRight, Check } from "lucide-react";
import { useState } from "react";
import { useGame } from "@/components/game-provider";
import { SiteHeader } from "@/components/site-header";
import { Button, Delta, PageHeader, Shell } from "@/components/ui";
import { sectors, surpriseEvents } from "@/lib/mock-data";
import { getNetAssets } from "@/lib/market-engine";
import { getNewsIssue } from "@/lib/news-engine";
export default function AdminGame(){const{teams,turn,nextTurn,minimumTurnover,baseRate,loanRate,activeRateHeadline,error,loading,gameCode}=useGame();const[selected,setSelected]=useState<string|null>(null);const[confirm,setConfirm]=useState(false);const submitted=teams.filter(t=>t.submitted).length;const selectedEvent=surpriseEvents.find(e=>e.id===selected);const firstNewsRelease=turn===1;const currentIssue=getNewsIssue(gameCode,turn);return <><SiteHeader admin/><Shell wide><PageHeader eyebrow="GAME MASTER · CONTROL ROOM" title="시장 관제실" description="팀의 선택과 시장의 숨은 흐름을 확인하세요." actions={<Button variant="danger" disabled={loading} onClick={()=>setConfirm(true)}>{firstNewsRelease?"첫 뉴스 공개 및 2턴 시작":"턴 마감 및 다음 뉴스 공개"} <ArrowRight size={16}/></Button>}/>
{error&&<div className="notice" role="alert"><strong>진행 오류:</strong> {error}</div>}
<div className="rate-banner"><div><span className="mono">RATE WATCH</span><strong>{activeRateHeadline}</strong></div><div><small>기준금리</small><b>{baseRate.toFixed(2)}%</b></div><div><small>은행 대출금리</small><b>{loanRate.toFixed(2)}%</b></div></div>
<div className="metric-grid"><div className="metric"><span>포트폴리오 제출</span><strong>{submitted} / {teams.length}</strong></div><div className="metric"><span>시장 심리</span><strong>과열</strong></div><div className="metric"><span>총 대출 잔액</span><strong>₩{(teams.reduce((sum,t)=>sum+t.loanBalance,0)/1000000).toFixed(0)}M</strong></div><div className="metric"><span>현재 선두</span><strong style={{fontFamily:"inherit",fontSize:20}}>{teams[0]?.name}</strong></div></div>
<div className="section-heading"><h2>팀 현황</h2><p>TURN {turn.toString().padStart(2,"0")} · 최소 변경률 {minimumTurnover}%</p></div><div className="table-scroll"><table className="data-table"><thead><tr><th>순위</th><th>팀명</th><th>순자산</th><th>대출·이자</th><th>누적 수익률</th><th>포트폴리오 변경률</th><th>주요 산업</th><th>제출</th></tr></thead><tbody>{teams.map(t=><tr key={t.id}><td className="rank-number">{t.rank.toString().padStart(2,"0")}</td><td><strong>{t.name}</strong></td><td className="number">₩{getNetAssets(t).toLocaleString()}</td><td className="number">₩{((t.loanBalance+t.accruedInterest)/1000000).toFixed(2)}M</td><td><Delta value={t.totalReturn}/></td><td><strong className={turn===1||t.turnoverRate>=minimumTurnover?"up":"down"}>{turn===1?"첫 턴 면제":`${t.turnoverRate}% / ${minimumTurnover}%`}</strong></td><td><span className="tag">{t.focus}</span></td><td>{t.submitted?<span className="tag tag-solid"><Check size={11}/> 완료</span>:<span className="tag">대기</span>}</td></tr>)}</tbody></table></div>
<div className="admin-grid"><section><div className="section-heading"><h2>시장 집중도</h2><p>팀 포트폴리오 합산</p></div><div className="analysis-bars">{sectors.map((sector,index)=>{const width=[34,17,14,10,9,7,5,4][index];return <div className="bar-row" key={sector}><span>{sector}</span><div className="bar-track"><div className="bar-fill" style={{width:`${width*2.5}%`,opacity:1-index*.07}}/></div><b className="number">{width}%</b></div>})}</div><div className="notice"><strong>시스템 관측:</strong> {turn===1?"초기 포트폴리오 편성 단계입니다. 아직 자동 이슈가 선택되지 않았습니다.":"직전 이슈와 공통 시장 요인이 있는 후속 이슈의 등장 확률이 높아집니다."}</div></section><section><div className="section-heading"><h2>자동 이슈</h2><p>관리자 전용</p></div><div style={{padding:"24px 0"}}><p className="eyebrow">{turn===1?"PRE-OPEN / LOCKED":"EVENT CHAIN / CONNECTED"}</p><h3 style={{fontFamily:"var(--font-noto-serif-kr)",fontSize:25,margin:"0 0 12px"}}>{currentIssue?.internalName??"첫 포트폴리오 편성 중"}</h3><p style={{color:"var(--muted)",fontSize:13,lineHeight:1.7}}>{currentIssue?.impact??"모든 팀이 초기 포트폴리오를 확정한 뒤 첫 뉴스가 생성됩니다."}</p><div className="notice">팀 화면에는 내부 이벤트명과 영향 계산이 공개되지 않습니다.</div></div></section></div>
<div className="section-heading"><h2>관리자 돌발 이슈</h2><p>2회 중 1회 남음 · 한 턴 최대 1회</p></div><div className="event-list">{surpriseEvents.map(event=><button key={event.id} className={`event-card ${selected===event.id?"selected":""}`} onClick={()=>setSelected(selected===event.id?null:event.id)}><span>{event.category}</span><strong>{event.headline}</strong><small>{event.impact}</small></button>)}</div>
{confirm&&<div className="modal-backdrop"><section className="modal"><button className="modal-close" onClick={()=>setConfirm(false)}>×</button><AlertTriangle color="var(--burgundy)"/><h2 style={{marginTop:14}}>{firstNewsRelease?"첫 뉴스를 공개할까요?":"현재 턴을 마감할까요?"}</h2><div className="notice">미제출 팀 {teams.length-submitted}개 · {firstNewsRelease?"수익률 적용 없이 첫 뉴스가 공개되고 2턴 편성이 시작됩니다.":"현재 공개된 뉴스가 수익률에 반영된 뒤 다음 뉴스가 공개됩니다."}{selectedEvent&&!firstNewsRelease&&<> 돌발 이슈 “{selectedEvent.headline}”도 함께 적용됩니다.</>}</div><p style={{fontSize:12,color:"var(--muted)"}}>{firstNewsRelease?"2턴 화면이 열리면 모든 팀의 제출 상태가 다시 대기로 바뀝니다.":"확정된 턴 결과는 되돌릴 수 없습니다. 마지막 턴 종료 시 팀별 포트폴리오·대출 원장은 삭제되고 익명 최종 결과만 보관됩니다."}</p><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><Button variant="paper" onClick={()=>setConfirm(false)}>취소</Button><Button variant="danger" disabled={loading} onClick={()=>{void nextTurn();setConfirm(false);setSelected(null)}}>{firstNewsRelease?"뉴스 공개":"턴 마감"}</Button></div></section></div>}</Shell></>}
