"use client";

import Link from "next/link";
import { Check, ChevronDown, ChevronUp, Landmark, LockKeyhole, Minus, Plus, Search, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { SiteHeader } from "@/components/site-header";
import { useGame } from "@/components/game-provider";
import { Button, Delta, MiniChart, Shell } from "@/components/ui";
import { companies, sectors } from "@/lib/mock-data";
import { getNewsSequence } from "@/lib/news-engine";
import type { Company, PortfolioPosition, Sector } from "@/lib/types";
import { calculatePortfolioTurnover } from "@/lib/portfolio-turnover";
import { CompanyDetailPopup } from "@/components/company-detail-popup";
import { NewsPaperPopup } from "@/components/news-paper-popup";
import { BANK_NAME, calculateCompanyReturn, getBorrowingLimit, getNetAssets, MAX_LOAN_AMOUNT } from "@/lib/market-engine";
import { getCompanyEvents } from "@/lib/company-events";

export default function Portfolio() {
  const { initialBudget, minimumTurnover, turn, currentPortfolio, currentBaselinePortfolio, currentTeam, error, reopenPortfolio, submitPortfolio, status, gameCode, baseRate, loanRate, activeRateHeadline, borrow, repay } = useGame();
  const [query,setQuery]=useState(""); const [market,setMarket]=useState("전체"); const [openSectors,setOpenSectors]=useState<Set<Sector>>(new Set(["AI·반도체"]));
  const [positions,setPositions]=useState<PortfolioPosition[]>([{companyId:"samsung-electronics",weight:40},{companyId:"sk-hynix",weight:35},{companyId:"ecopro-bm",weight:25}]); const [submitted,setSubmitted]=useState(false); const [editing,setEditing]=useState(false);
  const [detailCompany,setDetailCompany]=useState<Company|null>(null);
  const [loanAmount,setLoanAmount]=useState(10_000_000);
  useEffect(()=>{if(currentPortfolio.length&&!editing)queueMicrotask(()=>setPositions(currentPortfolio))},[currentPortfolio,editing]);
  useEffect(()=>{queueMicrotask(()=>setSubmitted(Boolean(currentTeam?.submitted)))},[currentTeam?.submitted]);
  const total=positions.reduce((sum,position)=>sum+position.weight,0); const remaining=Math.max(0,100-total); const initialSetup=turn===1; const issueSequence=getNewsSequence(gameCode,Math.max(0,turn-1)); const issue=issueSequence.at(-1)??null; const previousIssues=issueSequence.slice(-3,-1);
  const previousPositions=turn===1?[]:currentBaselinePortfolio; const turnover=calculatePortfolioTurnover(previousPositions,positions); const firstTurn=turn===1; const turnoverMet=firstTurn||turnover>=minimumTurnover; const canSubmit=total===100&&positions.length>0&&turnoverMet;
  const visibleCompanies=useMemo(()=>companies.filter(company=>(market==="전체"||company.market===market)&&company.name.includes(query)),[market,query]);
  function markEdited(){setEditing(true);if(submitted){setSubmitted(false);void reopenPortfolio().then(success=>{if(!success)setSubmitted(true)})}}
  function toggleCompany(id:string){const selected=positions.some(position=>position.companyId===id);if(selected)setPositions(positions.filter(position=>position.companyId!==id));else if(positions.length<8&&remaining>0)setPositions([...positions,{companyId:id,weight:0}]);else return;markEdited()}
  function toggleSector(sector:Sector){setOpenSectors(current=>{const next=new Set(current);if(next.has(sector))next.delete(sector);else next.add(sector);return next})}
  function changeWeight(id:string,value:number){const position=positions.find(item=>item.companyId===id);if(!position)return;const nextWeight=Math.max(0,Math.min(position.weight+remaining,value));if(nextWeight===position.weight)return;setPositions(positions.map(item=>item.companyId===id?{...item,weight:nextWeight}:item));markEdited()}
  async function submit(){const largest=[...positions].sort((a,b)=>b.weight-a.weight)[0];const focus=companies.find(company=>company.id===largest.companyId)?.sector??"AI·반도체";if(await submitPortfolio(positions,focus)){setEditing(false);setSubmitted(true)}}
  const companyEvents=useMemo(()=>initialSetup?[]:getCompanyEvents(turn),[initialSetup,turn]);
  const investmentValue=currentTeam?.assets??initialBudget; const debt=(currentTeam?.loanBalance??0)+(currentTeam?.accruedInterest??0); const netAssets=currentTeam?getNetAssets(currentTeam):initialBudget; const loanLimit=getBorrowingLimit(initialBudget,currentTeam?.loanBalance??0);
  function displayChange(company:Company){return issue?calculateCompanyReturn(company,issue,turn,0,companyEvents,previousIssues).total:0}
  if(status!=="playing")return <><SiteHeader/><Shell><section className="portfolio-locked"><LockKeyhole size={34}/><p className="eyebrow">PORTFOLIO ACCESS · LOCKED</p><h1>{status==="lobby"?"아직 시장이 열리지 않았습니다":"현재 포트폴리오를 편집할 수 없습니다"}</h1><p>{status==="lobby"?"관리자가 게임을 시작하면 초기 포트폴리오 편성 화면이 자동으로 열립니다. 대기 화면에서 진행 방법을 먼저 확인해주세요.":"시장 계산 또는 게임 종료 상태에서는 포트폴리오가 잠깁니다."}</p><Link href={status==="finished"?"/results":"/team/game"}><Button variant="paper">{status==="finished"?"최종 결과 보기":"팀 대기 화면으로"}</Button></Link></section></Shell></>;
  return <><SiteHeader/><main className="portfolio-workspace">
    <section className={`portfolio-newsline ${initialSetup?"preopen-newsline":""}`}><div className="portfolio-headline"><span className="mono">{initialSetup?"PRE-OPEN · INITIAL SETUP":`NOW · 제${turn}턴 헤드라인`}</span><strong>{issue?.headline??"개장 전입니다 — 초기 포트폴리오를 먼저 구성하세요"}</strong></div><div className="market-marquee"><div className="market-marquee-track">{[...companies.slice(0,12),...companies.slice(0,12)].map((company,index)=><span key={`${company.id}-${index}`}><b>{company.name}</b> ₩{company.price.toLocaleString()} {initialSetup?<em>기준가</em>:<Delta value={displayChange(company)}/>}</span>)}</div></div></section>
    <header className="portfolio-workspace-head"><div><p className="eyebrow">PORTFOLIO EDITOR · TURN {turn.toString().padStart(2,"0")}</p><h1>포트폴리오 조정</h1>{error&&<p className="portfolio-error" role="alert">{error}</p>}</div><div className="portfolio-summary">{issue&&<NewsPaperPopup key={`${turn}-${issue.id}`} issue={issue} turn={turn}/>}<span>선택 <b>{positions.length}/8</b></span><span>배분 <b>{total}%</b></span><span>변경률 <b className={turnoverMet?"up":"down"}>{firstTurn?"면제":`${turnover}%`}</b></span><span>남은 비중 <b className={total===100?"up":total>100?"down":""}>{100-total}%</b></span><Button variant={submitted?"gold":"ink"} disabled={!canSubmit} onClick={()=>void submit()}>{submitted?<><Check size={15}/> 확정 완료</>:!turnoverMet?`${minimumTurnover-turnover}% 더 변경 필요`:"포트폴리오 확정"}</Button></div></header>
    <section className="bank-desk"><div className="bank-title"><Landmark size={19}/><div><small>TURN LOAN · {initialSetup?"LOCKED":"OPEN"}</small><strong>{BANK_NAME}</strong></div></div><div className="rate-quote"><span>기준금리 <b>{baseRate.toFixed(2)}%</b></span><span>대출금리 <b>{loanRate.toFixed(2)}%</b></span><small>{activeRateHeadline}</small></div><label><span>거래 금액</span><select value={loanAmount} disabled={initialSetup} onChange={event=>setLoanAmount(Number(event.target.value))}><option value="5000000">500만원</option><option value="10000000">1,000만원</option><option value="20000000">2,000만원</option></select></label><div className="bank-actions"><Button variant="gold" disabled={initialSetup||!currentTeam||loanAmount>loanLimit} onClick={()=>currentTeam&&void borrow(currentTeam.id,loanAmount)}>대출</Button><Button variant="paper" disabled={initialSetup||!currentTeam||debt===0} onClick={()=>currentTeam&&void repay(currentTeam.id,Math.min(loanAmount,debt))}>상환</Button></div><p>{initialSetup?"첫 포트폴리오를 확정할 때까지 대출이 잠깁니다.":`남은 한도 ₩${loanLimit.toLocaleString()} · 게임 최대 ₩${MAX_LOAN_AMOUNT.toLocaleString()} · 매 턴 이자 부과`}</p></section>
    <div className="portfolio-split">
      <section className="allocation-editor"><div className="pane-title"><div><p className="eyebrow">MY ALLOCATION</p><h2>선택 종목과 비중</h2></div><span className={canSubmit?"ready-copy":""}>{canSubmit?"제출할 준비가 됐습니다":total!==100?`합계 ${total}% · 100%로 맞춰주세요`:`최소 ${minimumTurnover}% 변경이 필요합니다`}</span></div>
        {!firstTurn&&<div className="turnover-progress"><div><span>직전 턴 대비 변경률</span><b className={turnoverMet?"up":"down"}>{turnover}% / {minimumTurnover}%</b></div><i><span style={{width:`${Math.min(100,(turnover/minimumTurnover)*100)}%`}}/></i><small>{turnoverMet?"변경 조건을 충족했습니다.":`${minimumTurnover-turnover}%를 더 조정해야 제출할 수 있습니다.`}</small></div>}
        {firstTurn&&<div className="first-turn-note">첫 턴은 이전 포트폴리오가 없어 최소 변경률 검사를 적용하지 않습니다.</div>}
        <div className="allocation-list">{positions.map(position=>{const company=companies.find(item=>item.id===position.companyId)!;const previousWeight=previousPositions.find(item=>item.companyId===position.companyId)?.weight??0;const difference=position.weight-previousWeight;return <article className="allocation-item" key={position.companyId}><div className="allocation-company"><small>{company.market} · {company.code}</small><strong>{company.name}</strong><span>{company.sector} · {initialSetup?"초기 편성":<>직전 {previousWeight}% · <em className={difference>=0?"up":"down"}>{difference>0?"▲ +":difference<0?"▼ ":""}{difference}%p</em></>}</span></div>{initialSetup?<span className="mono">기준가</span>:<Delta value={displayChange(company)}/>}<div className="weight-control"><button aria-label={`${company.name} 비중 줄이기`} disabled={position.weight===0} onClick={()=>changeWeight(company.id,position.weight-5)}><Minus size={13}/></button><label><input aria-label={`${company.name} 비중`} type="number" min="0" max={position.weight+remaining} value={position.weight} onChange={event=>changeWeight(company.id,Number(event.target.value))}/><span>%</span></label><button aria-label={`${company.name} 비중 늘리기`} disabled={remaining===0} onClick={()=>changeWeight(company.id,position.weight+5)}><Plus size={13}/></button></div><button className="remove-position" aria-label={`${company.name} 제거`} onClick={()=>toggleCompany(company.id)}><Trash2 size={15}/></button></article>})}</div>
        {positions.length===0&&<div className="empty-allocation"><p>아직 선택한 기업이 없습니다.</p><small>오른쪽 산업군을 열어 기업을 추가하세요.</small></div>}
        <div className="allocation-visual">{positions.map((position,index)=><i key={position.companyId} style={{width:`${position.weight}%`,background:["var(--burgundy)","var(--mustard)","var(--fall)","var(--green)","#8c7460"][index]}} title={`${companies.find(item=>item.id===position.companyId)?.name} ${position.weight}%`}/>)}</div>
        <div className="budget-note"><span>현재 투자 평가액</span><b>₩{investmentValue.toLocaleString()}</b><small>총부채 ₩{debt.toLocaleString()} · 부채 차감 순자산 ₩{netAssets.toLocaleString()}</small></div>
      </section>
      <section className="company-browser"><div className="company-browser-tools"><label><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="기업명 검색"/></label><select value={market} onChange={event=>setMarket(event.target.value)}><option value="전체">전체 시장</option><option value="코스피">코스피</option><option value="코스닥">코스닥</option></select></div>
        <div className="sector-accordions">{sectors.map(sector=>{const open=openSectors.has(sector);const sectorCompanies=visibleCompanies.filter(company=>company.sector===sector);const sectorChange=sectorCompanies.length?sectorCompanies.reduce((sum,company)=>sum+displayChange(company),0)/sectorCompanies.length:0;return <section className={`sector-accordion ${open?"sector-open":""}`} key={sector}><button className="sector-toggle" onClick={()=>toggleSector(sector)} aria-expanded={open}><div><small>INDUSTRY</small><strong>{sector}</strong></div><span>{sectorCompanies.length}개 기업</span>{!initialSetup&&sectorCompanies.length>0&&<Delta value={sectorChange}/>} {open?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>
          {open&&<div className="sector-company-list">{sectorCompanies.length===0?<p className="sector-empty">현재 필터에 맞는 기업이 없습니다.</p>:sectorCompanies.map(company=>{const selected=positions.some(position=>position.companyId===company.id);const addDisabled=!selected&&(positions.length>=8||remaining===0);return <article className={`browser-company ${selected?"company-selected":""}`} key={company.id}><div className="browser-company-main"><small>{company.market} · {company.code}</small><button onClick={()=>setDetailCompany(company)}>{company.name}</button><span>{company.description}</span></div><MiniChart values={company.history}/><div className="browser-company-price"><strong>₩{company.price.toLocaleString()}</strong>{initialSetup?<small>개장 기준가</small>:<Delta value={displayChange(company)}/>}</div><Button variant={selected?"gold":"paper"} disabled={addDisabled} onClick={()=>toggleCompany(company.id)}>{selected?"선택됨":remaining===0?"배분 완료":"추가"}</Button></article>})}</div>}
        </section>})}</div>
      </section>
    </div>
  </main>{detailCompany&&<CompanyDetailPopup company={detailCompany} onClose={()=>setDetailCompany(null)}/>}</>;
}
