"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { companies, rateEvents, teams as mockTeams } from "@/lib/mock-data";
import { getMoodFromState, getNewsSequence, getSectorAttention, selectNextNewsIssue } from "@/lib/news-engine";
import { calculateCompanyReturn, DEFAULT_BASE_RATE, getLoanRate } from "@/lib/market-engine";
import { getCompanyEvents } from "@/lib/company-events";
import { callGameApi } from "@/lib/game-api";
import { isSupabaseConfigured, supabase } from "@/lib/supabase/client";
import { calculateInvestorMetrics } from "@/lib/investor-metrics";
import type { MarketEvent } from "@/lib/event-catalog";
import type { CompanyEvent, FinalResult, InvestorMetrics, NewsIssue, PersistedNews, PortfolioPosition, Sector, SurpriseEvent, Team } from "@/lib/types";

type GameStatus="lobby"|"playing"|"calculating"|"finished";
type Credentials={teamId:string;teamToken:string;adminToken:string};
type RemoteTeam={id:string;rank:number;previous_rank:number;name:string;assets:number;total_return:number;turn_return:number;submitted:boolean;focus:Sector;turnover_rate:number;loan_balance:number;accrued_interest:number;portfolio:PortfolioPosition[];previous_portfolio:PortfolioPosition[]};
type RemoteFinalResult={id:string;team_number:number;team_name:string|null;final_rank:number;final_net_assets:number;total_return:number;turn_return:number;investor_metrics:Partial<InvestorMetrics>};
type RemoteNewsBoard={turn:number;issue:NewsIssue;company_events:CompanyEvent[];surprise_event:SurpriseEvent|null;market_mood:{label:string;score:number};sector_attention:Partial<Record<Sector,number>>};
const mapTeam=(team:RemoteTeam):Team=>({id:team.id,rank:team.rank,previousRank:team.previous_rank,name:team.name,assets:Number(team.assets),totalReturn:Number(team.total_return),turnReturn:Number(team.turn_return),submitted:team.submitted,focus:team.focus,turnoverRate:Number(team.turnover_rate),loanBalance:Number(team.loan_balance),accruedInterest:Number(team.accrued_interest),portfolio:team.portfolio??[],previousPortfolio:team.previous_portfolio??[]});
const defaultInvestorMetrics:InvestorMetrics={concentration:50,sectorCount:3,volatility:50,turnover:50,newsReaction:50,contrarian:50,holdDuration:50,dipBuying:50,profitTaking:50,largeCapShare:50,smallCapShare:50,timingScore:50};
const mapFinalResult=(result:RemoteFinalResult):FinalResult=>({id:result.id,teamName:result.team_name??`TEAM ${String(result.team_number).padStart(2,"0")}`,rank:result.final_rank,assets:Number(result.final_net_assets),totalReturn:Number(result.total_return),turnReturn:Number(result.turn_return),metrics:{...defaultInvestorMetrics,...Object.fromEntries(Object.entries(result.investor_metrics??{}).map(([key,value])=>[key,Number(value)]))}});
const mapNews=(news:RemoteNewsBoard):PersistedNews=>({turn:news.turn,issue:news.issue,companyEvents:news.company_events??[],surpriseEvent:news.surprise_event??null,marketMood:news.market_mood??{label:"중립",score:50},sectorAttention:news.sector_attention??{}});

interface GameContextValue{teams:Team[];finalResults:FinalResult[];newsHistory:PersistedNews[];currentNews:PersistedNews|null;surpriseUsed:number;currentTeam:Team|null;currentPortfolio:PortfolioPosition[];currentBaselinePortfolio:PortfolioPosition[];gameCode:string;status:GameStatus;turn:number;totalTurns:number;initialBudget:number;minimumTurnover:number;maxTeams:number;baseRate:number;loanRate:number;activeRateHeadline:string;connectionMode:"supabase"|"local";loading:boolean;error:string;addTeam:(name:string,code:string)=>Promise<boolean>;createGame:(name:string,totalTurns:number,budget:number,turnover:number,maxTeams:number)=>Promise<boolean>;selectGame:(code:string)=>Promise<boolean>;startGame:()=>Promise<void>;nextTurn:(surprise?:SurpriseEvent|null)=>Promise<void>;borrow:(teamId:string,amount:number)=>Promise<boolean>;repay:(teamId:string,amount:number)=>Promise<boolean>;reopenPortfolio:()=>Promise<boolean>;submitPortfolio:(positions:PortfolioPosition[],focus:Sector)=>Promise<boolean>;refresh:()=>Promise<void>}
const GameContext=createContext<GameContextValue|null>(null);

export function GameProvider({children}:{children:React.ReactNode}){
  const[teams,setTeams]=useState<Team[]>(isSupabaseConfigured?[]:mockTeams.slice(0,4));const[finalResults,setFinalResults]=useState<FinalResult[]>([]);const[newsHistory,setNewsHistory]=useState<PersistedNews[]>([]);const[surpriseUsed,setSurpriseUsed]=useState(0);const[currentTeam,setCurrentTeam]=useState<Team|null>(null);const[currentPortfolio,setCurrentPortfolio]=useState<PortfolioPosition[]>([]);const[currentBaselinePortfolio,setCurrentBaselinePortfolio]=useState<PortfolioPosition[]>([]);
  const[gameCode,setGameCode]=useState(()=>typeof window==="undefined"?"":localStorage.getItem("jongga.gameCode")??"");const[status,setStatus]=useState<GameStatus>("lobby");const[turn,setTurn]=useState(1);const[totalTurns,setTotalTurns]=useState(8);const[initialBudget,setInitialBudget]=useState(100000000);const[minimumTurnover,setMinimumTurnover]=useState(20);const[maxTeams,setMaxTeams]=useState(12);const[baseRate,setBaseRate]=useState(DEFAULT_BASE_RATE);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
  const[credentials,setCredentials]=useState<Credentials>(()=>typeof window==="undefined"?{teamId:"",teamToken:"",adminToken:""}:{teamId:localStorage.getItem("jongga.teamId")??"",teamToken:localStorage.getItem("jongga.teamToken")??"",adminToken:localStorage.getItem("jongga.adminToken")??""});

  const refresh=useCallback(async()=>{if(!isSupabaseConfigured||!gameCode)return;try{const data=await callGameApi<{game:{status:GameStatus;current_turn:number;total_turns:number;initial_budget:number;minimum_turnover:number;max_teams:number;base_rate:number};standings:Array<{team_id:string;team_name:string;rank:number;net_assets:number;total_return:number;submitted:boolean}>;finalResults:RemoteFinalResult[];newsBoard:RemoteNewsBoard[];surpriseUsed:number;team?:RemoteTeam;teams?:RemoteTeam[]}>({action:"sync",code:gameCode,teamId:credentials.teamId,teamToken:credentials.teamToken,adminToken:credentials.adminToken});setStatus(data.game.status);setTurn(data.game.current_turn);setTotalTurns(data.game.total_turns);setInitialBudget(Number(data.game.initial_budget));setMinimumTurnover(Number(data.game.minimum_turnover));setMaxTeams(data.game.max_teams);setBaseRate(Number(data.game.base_rate));setFinalResults((data.finalResults??[]).map(mapFinalResult));setNewsHistory((data.newsBoard??[]).map(mapNews));setSurpriseUsed(Number(data.surpriseUsed??0));if(data.teams)setTeams(data.teams.map(mapTeam));else setTeams(data.standings.map(item=>({id:item.team_id,rank:item.rank,previousRank:item.rank,name:item.team_name,assets:Number(item.net_assets),totalReturn:Number(item.total_return),turnReturn:0,submitted:item.submitted,focus:"AI·반도체",turnoverRate:0,loanBalance:0,accruedInterest:0})));if(data.team){setCurrentTeam(mapTeam(data.team));setCurrentPortfolio(data.team.portfolio??[]);setCurrentBaselinePortfolio(data.team.previous_portfolio??[])}}catch(reason){setError(reason instanceof Error?reason.message:"동기화에 실패했습니다.")}},[credentials,gameCode]);
  useEffect(()=>{queueMicrotask(()=>void refresh())},[refresh]);
  useEffect(()=>{const client=supabase;if(!client||!gameCode)return;const channel=client.channel(`jongga-${gameCode}`).on("postgres_changes",{event:"*",schema:"public",table:"games"},()=>void refresh()).on("postgres_changes",{event:"*",schema:"public",table:"team_standings"},()=>void refresh()).on("postgres_changes",{event:"*",schema:"public",table:"news_board"},()=>void refresh()).subscribe();return()=>{void client.removeChannel(channel)}},[gameCode,refresh]);
  const currentNews=newsHistory.find((news)=>news.turn===turn)??null;

  const value=useMemo<GameContextValue>(()=>({teams,finalResults,newsHistory,currentNews,surpriseUsed,currentTeam,currentPortfolio,currentBaselinePortfolio,gameCode,status,turn,totalTurns,initialBudget,minimumTurnover,maxTeams,baseRate,loanRate:getLoanRate(baseRate),activeRateHeadline:turn===1?"개장 전 · 초기 포트폴리오 편성":rateEvents[(turn-2)%rateEvents.length].headline,connectionMode:isSupabaseConfigured?"supabase":"local",loading,error,refresh,
    async addTeam(name,code){setLoading(true);setError("");try{const normalized=code.trim().toUpperCase();const data=await callGameApi<{teamId:string;teamToken:string;team:RemoteTeam}>({action:"join",code:normalized,name});localStorage.setItem("jongga.gameCode",normalized);localStorage.setItem("jongga.teamId",data.teamId);localStorage.setItem("jongga.teamToken",data.teamToken);localStorage.removeItem("jongga.adminToken");setFinalResults([]);setNewsHistory([]);setGameCode(normalized);setCredentials({teamId:data.teamId,teamToken:data.teamToken,adminToken:""});setCurrentTeam(mapTeam(data.team));return true}catch(reason){setError(reason instanceof Error?reason.message:"참가하지 못했습니다.");return false}finally{setLoading(false)}},
    async createGame(name,turnCount,budget,turnover,teamLimit){setLoading(true);setError("");try{const data=await callGameApi<{gameCode:string;adminToken:string}>({action:"create_game",name,totalTurns:turnCount,initialBudget:budget,minimumTurnover:turnover,maxTeams:teamLimit});localStorage.setItem("jongga.gameCode",data.gameCode);localStorage.setItem("jongga.adminToken",data.adminToken);localStorage.removeItem("jongga.teamId");localStorage.removeItem("jongga.teamToken");setGameCode(data.gameCode);setCredentials({teamId:"",teamToken:"",adminToken:data.adminToken});setTeams([]);setFinalResults([]);setNewsHistory([]);setCurrentTeam(null);return true}catch(reason){setError(reason instanceof Error?reason.message:"게임을 만들지 못했습니다.");return false}finally{setLoading(false)}},
    async selectGame(code){setLoading(true);setError("");try{const normalized=code.trim().toUpperCase();await callGameApi({action:"sync",code:normalized});localStorage.setItem("jongga.gameCode",normalized);setFinalResults([]);setNewsHistory([]);setGameCode(normalized);return true}catch(reason){setError(reason instanceof Error?reason.message:"게임을 찾지 못했습니다.");return false}finally{setLoading(false)}},
    async startGame(){setLoading(true);setError("");try{await callGameApi({action:"start",code:gameCode,adminToken:credentials.adminToken});await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"게임을 시작하지 못했습니다.")}finally{setLoading(false)}},
    async nextTurn(surprise=null){setLoading(true);setError("");setStatus("calculating");try{const persisted=currentNews?.issue as MarketEvent|undefined;const fallback=getNewsSequence(gameCode,Math.max(0,turn-1));const issue=persisted??fallback.at(-1)??null;const previousIssues=(newsHistory.length?newsHistory.map((news)=>news.issue):fallback).slice(-3,-1);const currentRateChange=turn===1?0:rateEvents[(turn-2)%rateEvents.length].change;const nextRateEvent=rateEvents[(turn-1)%rateEvents.length];const nextRate=Math.max(1,Math.min(7,baseRate+nextRateEvent.change));const companyEvents=currentNews?.companyEvents??(turn===1?[]:getCompanyEvents(turn));const combinedIssue=issue?{...issue,id:`${issue.id}-${surprise?.id??"auto"}`,factors:{...issue.factors,...Object.fromEntries(new Set([...Object.keys(issue.factors),...Object.keys(surprise?.factors??{})]).values().map((factor)=>[factor,Number(issue.factors[factor as keyof typeof issue.factors]??0)+Number(surprise?.factors[factor as keyof typeof surprise.factors]??0)]))}}:null;const returns=combinedIssue?Object.fromEntries(companies.map(company=>[company.id,calculateCompanyReturn(company,combinedIssue,turn,currentRateChange,companyEvents,previousIssues).total])):{};const attention=getSectorAttention(teams);const companyEventHistory=newsHistory.flatMap((news)=>news.companyEvents);const nextTurnNumber=turn+1;let nextNews=null;if(nextTurnNumber<=totalTurns){const history=(newsHistory.length?newsHistory.map((news)=>news.issue):fallback) as MarketEvent[];const selected=selectNextNewsIssue(gameCode,nextTurnNumber,history,attention,surprise);nextNews={turn:nextTurnNumber,issue:selected.issue,companyEvents:getCompanyEvents(nextTurnNumber,2,companyEventHistory),surpriseEvent:surprise,marketMood:getMoodFromState(selected.marketState),sectorAttention:attention,marketState:selected.marketState};}const investorMetrics=Object.fromEntries(teams.map(team=>[team.id,calculateInvestorMetrics(team.portfolio??[],team.previousPortfolio??[],team.turnoverRate,team.turnReturn,team.totalReturn)]));await callGameApi({action:"advance",code:gameCode,adminToken:credentials.adminToken,baseRate:nextRate,returns,investorMetrics,surpriseEvent:surprise,nextNews});await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"턴을 진행하지 못했습니다.");setStatus("playing")}finally{setLoading(false)}},
    async borrow(teamId,amount){try{await callGameApi({action:"loan",code:gameCode,mode:"borrow",teamId,teamToken:credentials.teamToken,amount});await refresh();return true}catch(reason){setError(reason instanceof Error?reason.message:"대출에 실패했습니다.");return false}},async repay(teamId,amount){try{await callGameApi({action:"loan",code:gameCode,mode:"repay",teamId,teamToken:credentials.teamToken,amount});await refresh();return true}catch(reason){setError(reason instanceof Error?reason.message:"상환에 실패했습니다.");return false}},
    async reopenPortfolio(){setError("");setCurrentTeam(team=>team?{...team,submitted:false}:team);setTeams(items=>items.map(team=>team.id===credentials.teamId?{...team,submitted:false}:team));if(!isSupabaseConfigured)return true;try{await callGameApi({action:"reopen_portfolio",code:gameCode,teamId:credentials.teamId,teamToken:credentials.teamToken});return true}catch(reason){setError(reason instanceof Error?reason.message:"포트폴리오 수정 상태를 반영하지 못했습니다.");await refresh();return false}},async submitPortfolio(positions,focus){setError("");try{await callGameApi({action:"submit_portfolio",code:gameCode,teamId:credentials.teamId,teamToken:credentials.teamToken,positions,focus});await refresh();return true}catch(reason){setError(reason instanceof Error?reason.message:"포트폴리오 제출에 실패했습니다.");return false}},
  }),[baseRate,credentials,currentBaselinePortfolio,currentNews,currentPortfolio,currentTeam,error,finalResults,gameCode,initialBudget,loading,maxTeams,minimumTurnover,newsHistory,refresh,status,surpriseUsed,teams,totalTurns,turn]);
  return <GameContext.Provider value={value}>{children}</GameContext.Provider>;
}
export function useGame(){const context=useContext(GameContext);if(!context)throw new Error("useGame must be used within GameProvider");return context}
